using './smarttaskmanager-api-containerapp.module.bicep'

param aca_env_outputs_azure_container_apps_environment_default_domain = '{{ .Env.ACA_ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}'
param aca_env_outputs_azure_container_apps_environment_id = '{{ .Env.ACA_ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param aca_env_outputs_azure_container_registry_endpoint = '{{ .Env.ACA_ENV_AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param aca_env_outputs_azure_container_registry_managed_identity_id = '{{ .Env.ACA_ENV_AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param apiauthorizationrequiredscope_value = '{{ parameter "apiAuthorizationRequiredScope" }}'
param apiazureadaudience_value = '{{ parameter "apiAzureAdAudience" }}'
param apiazureadclientid_value = '{{ parameter "apiAzureAdClientId" }}'
param apiazureadinstance_value = '{{ parameter "apiAzureAdInstance" }}'
param apiazureadtenantid_value = '{{ parameter "apiAzureAdTenantId" }}'
param smarttaskmanager_api_containerimage = '{{ .Image }}'
param smarttaskmanager_api_containerport = '{{ targetPortOrDefault 8080 }}'
param smarttaskmanagersqlconnectionstring_value = '{{ securedParameter "smartTaskManagerSqlConnectionString" }}'
