using './smarttaskmanager-web-containerapp.module.bicep'

param aca_env_outputs_azure_container_apps_environment_default_domain = '{{ .Env.ACA_ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}'
param aca_env_outputs_azure_container_apps_environment_id = '{{ .Env.ACA_ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param aca_env_outputs_azure_container_registry_endpoint = '{{ .Env.ACA_ENV_AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param aca_env_outputs_azure_container_registry_managed_identity_id = '{{ .Env.ACA_ENV_AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param smarttaskmanager_web_containerimage = '{{ .Image }}'
param smarttaskmanager_web_containerport = '{{ targetPortOrDefault 8080 }}'
param smarttaskmanagerapiaudience_value = '{{ parameter "smartTaskManagerApiAudience" }}'
param smarttaskmanagerapiscopes_value = '{{ parameter "smartTaskManagerApiScopes" }}'
param webazureadcallbackpath_value = '{{ parameter "webAzureAdCallbackPath" }}'
param webazureadclientid_value = '{{ parameter "webAzureAdClientId" }}'
param webazureadclientsecret_value = '{{ securedParameter "webAzureAdClientSecret" }}'
param webazureadinstance_value = '{{ parameter "webAzureAdInstance" }}'
param webazureadsignedoutcallbackpath_value = '{{ parameter "webAzureAdSignedOutCallbackPath" }}'
param webazureadtenantid_value = '{{ parameter "webAzureAdTenantId" }}'
